Validate SDMX-ML v2.1 messages
khaeru/sdmx pull request #154
Opened 2024-01-11 15:36 UTC by goatsweater

Add support for validating SDMX-ML messages via `sdmx.validate_xml()` (Closes https://github.com/khaeru/sdmx/issues/51).

This replaces #153.

### PR checklist
- [ ] Checks all ✅
- [ ] Update documentation
- [ ] Update doc/whatsnew.rst

2024-01-12 10:33 UTC, khaeru requested changes
Excellent, thanks for the rebase.

The code already looks quite clean and simple, which is great. I have some minor (stylistic) and medium-size requests, below. If you like, or if they are not clear, I can add some commits to the branch to address some or all of them; or you could handle them yourself. Please let me know.

Once we've treated those, I can hop in and add some small or parametrized test cases to ensure we have full coverage.

2024-01-12 10:33 UTC, khaeru commented on .github/workflows/sources.yaml
> +      run: pip install .[cache,tests,validation]
Note this doesn't match the added optional deps ("validation" != "validate"). However see comment on pyproject.toml, below.

2024-01-12 10:33 UTC, khaeru commented on doc/howto/validate.rst
> +Validate SDMX-ML against official schemas
A HOWTO is great to have.

Generally, for ReST files we have each sentence start on a new line, with no hard-wrapping within sentences. (This makes it easier to read diffs as the docs are edited. I also should add this to the code style guide.)

2024-01-12 10:33 UTC, khaeru commented on doc/whatsnew.rst
> +-Add support for validating SDMX-ML messages via sdmx.validate_xml() (Closes #51)
- Begin bullet item with hyphen, space: `- Add support …`
- Use :func: here as well.
- In parentheses, you can use the :issue: and :pull: roles.

All in all, something like this:
```
- Add support for validating SDMX-ML messages; see :func:`.validate_xml` (:issue:`51`; thanks :user:`goatsweater` for :pull:`154`).
```

2024-01-12 10:33 UTC, khaeru commented on pyproject.toml
> +validate = ["platformdirs"]
This is the right library to use for this purpose.

I've just checked and found that platformdirs supports Python >= 3.8, that is, all currently-maintained versions of Python. This is the same as sdmx1. It's also (IMHO) a well-maintained package that is a dependency of, for instance, Jupyter.

So, I think it is fine to make this a mandatory dependency, rather than an optional one. This means you could drop the changes to the GitHub Actions workflows, and also the try/except block where platformdirs is imported in the new functions.

2024-01-12 10:33 UTC, khaeru commented on sdmx/writer/xml.py
> +def validate_xml(msg: Union[Path, IO], schema_dir: Optional[Path] = None) -> bool:
Two things:
1. On reflection, this function is useful for *any* SDMX-ML formatted file or document; even one that is not written by this `sdmx` package. So I think perhaps the module `sdmx.format.xml.common` is the best place for these functions, as they pertain to the SDMX-ML format *in general*.
2. Both `validate_xml` and `install_schemas` should be "future-proof" for SDMX-ML 3.0. That's not to say you have to do that in this PR but, for instance:
   - The docstrings could mention SDMX-ML 2.1 specifically, or that 3.0 is not yet supported/to be added in the future.
   - `validate_xml()` could either (a) take a version= parameter (and for now, default to "2.1" and raise NotImplementedError if the user gives "3.0"); or (b) detect the version, for instance by inspecting the XML namespaces in the top-level tags.
   - `install_schemas()` could either (a) take a version= parameter, as above; or (b) install both sets of schemas.

2024-01-12 14:00 UTC, goatsweater commented on pyproject.toml
> +validate = ["platformdirs"]
Good points. I was hesitant of introducing a new dependency because its only value is in this narrow case. I do think the user experience of having it be mandatory will be nicer though as things will "just work".

2024-01-12 14:19 UTC, goatsweater commented on .github/workflows/sources.yaml
> +      run: pip install .[cache,tests,validation]
Silly error. Sorry about that.

2024-01-12 15:59 UTC, goatsweater commented on sdmx/writer/xml.py
> +def validate_xml(msg: Union[Path, IO], schema_dir: Optional[Path] = None) -> bool:
I'm going to take a bit of time thinking through how to handle the different versions of the schemas. Supporting 3.0 would be ideal.

For the moment I've moved the code into `format.xml` and marked this as a draft until I can try out some ideas for supporting multiple schema versions.

2024-01-13 01:20 UTC, goatsweater commented
@khaeru I could use your help with generating XML for an unsupported message type. I have a test for an invalid message - I need to generate something that is *not* a message and I'm actually not sure how to do that. I tried just creating a `DataSet` and sending it through `to_xml()`, but that throws an exception and I'm not entirely sure why. I tried to copy/reuse code from `test_dataset_bare.py`.

Just for reference here is what I tried (inside a test function):

```python
msg_path = tmp_path / "invalid.xml"

ds = v21.DataSet()
key = v21.Key(
        FREQ="D",
        CURRENCY="NZD",
        CURRENCY_DENOM="EUR",
        EXR_TYPE="SP00",
        EXR_SUFFIX="A",
        TIME_PERIOD="2013-01-18",
)
obs_status = v21.DataAttribute(id="OBS_STATUS")
attr = {"OBS_STATUS": v21.AttributeValue(value_for=obs_status, value="A")}
ds.obs.append(v21.Observation(dimension=key, value=1.5931, attached_attribute=attr))
key = key.copy(TIME_PERIOD="2013-01-21")
ds.obs.append(v21.Observation(dimension=key, value=1.5925, attached_attribute=attr))

msg_path.write_bytes(sdmx.to_xml(ds))
``` 

It raises this exception:

```
sdmx/writer/xml.py:50: in to_xml
    return etree.tostring(writer.recurse(obj), **kwargs)
sdmx/writer/base.py:53: in recurse
    return dispatcher(obj, *args, **kwargs)
/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/functools.py:889: in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
sdmx/writer/xml.py:717: in _ds
    elem.append(writer.recurse(obs, struct_spec=struct_spec))
sdmx/writer/base.py:53: in recurse
    return dispatcher(obj, *args, **kwargs)
/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/functools.py:889: in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
sdmx/writer/xml.py:667: in _obs
    elem.append(_kv("gen:ObsKey", obj.dimension))
```

2024-01-15 09:14 UTC, khaeru commented
There are multiple ways to approach that:
- One way is to take any existing XML specimen from https://github.com/khaeru/sdmx-test-data, for instance the file TEST/gh-142.xml related to #142, copy it, and manually edit the XML.
- Another way is something like this:
  ```python
  import re

  import sdmx

  # Minimal/empty message
  msg = sdmx.message.StructureMessage()

  # - Write a valid message to XML.
  # - Use regex to change the name of the outermost tag to something invalid.
  re.sub(b"mes:Structure([ >])", br"mes:FooBar\1", sdmx.to_xml(msg))
  ```
  This gives output like:
  ```xml
  <?xml version='1.0' encoding='utf-8'?>
  <mes:FooBar
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:com="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/common"
    xmlns:md="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/metadata/generic"
    xmlns:data="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/data/structurespecific"
    xmlns:str="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/structure"
    xmlns:mes="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message"
    xmlns:gen="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/data/generic"
    xmlns:footer="http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message/footer">
    <mes:Header>
      <mes:Test>false</mes:Test>
    </mes:Header>
    <mes:Structures/>
  </mes:FooBar>
  ```
  You can then put this into an io.BytesIO or write it to a file to use in your test.

2024-01-17 09:36 UTC, khaeru approved these changes
Excellent! Thanks for a high quality contribution, including thorough tests and documentation/HOWTO. Much appreciated.

I will merge this and then prepare a release.

Some thoughts on next steps, mainly for my own reference:
- The similar parts of `test_validate_xml_from_v{2_1,3_0}_samples()` could be split into a common utility function/fixture.
- `test_validate_xml_invalid_doc()` raises the important question of whether `sdmx.to_xml()` should *ever* generate invalid SDMX-ML—or put another way, whether it should *guarantee* valid SDMX-ML. I think this would be a nice enhancement to `.writer.xml`, but would require detailed tests to support.
- Since the schemas change slowly, we could enhance `install_schemas()` to store a marker (like the Git commit hash for the version downloaded) and skip re-downloading and installing if it has not changed. This could improve performance, especially if users are careless about calling the function repeatedly.

2024-01-17 09:38 UTC, merged

2024-01-17 09:49 UTC, khaeru commented
I see [here](https://github.com/khaeru/sdmx/actions/runs/7553757969/job/20565193404#step:7:1206) that the first run of the "pytest" workflow fails on `main` with: 
```
requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
```

This only occurs for one of the jobs. I think I also saw this at one point during work on the PR, and the job succeeded when re-run. So this means these tests can be "flaky" in the sense that they rely on a certain expected response from the GitHub API—if that isn't given for any reason (e.g. momentary network interruption), then this line tries to use `zipball_url=None`:
https://github.com/khaeru/sdmx/blob/e76b5201e917e5c9e46f58a56d3472c7d2a546a5/sdmx/format/xml/common.py#L207-L208

I will mitigate this by applying a pytest mark to re-run these tests as necessary until a correct response is received.