Add a new source with tests and doc for NBB (National Bank of Belgium)
khaeru/sdmx pull request #32
Opened 2020-12-03 17:35 UTC by bertrandmarc

@khaeru please find attached a new source for the National Bank of Belgium. As STAT_EE, it is based on the same server as the OECD, hence limited to SDMX 2.0 and SDMX-json.

2020-12-04 15:15 UTC, khaeru requested changes
@bertrandmarc again thanks for the contribution. Please see comments, also #33 for how to add a line to doc/whatsnew.rst with the PR number and linking to the new source.

2020-12-04 15:15 UTC, khaeru commented on doc/sources.rst
> +-----------------------------------------
As in the other PR, the underline must at least match the length of the title. If you test compile the docs (`cd docs && make html`) it will complain about this.

2020-12-04 15:15 UTC, khaeru commented on sdmx/tests/test_source.py
> +    assert len(source_ids) == 18
Because #33 also modifies this line, this PR branch will need to be rebased after that one is merged.

2020-12-10 16:24 UTC, khaeru commented on sdmx/tests/test_source.py
> +    assert len(source_ids) == 18
@bertrandmarc #33 is now merged. Are you comfortable to rebase this branch, or should I do it for you and force push?

2020-12-12 15:03 UTC, bertrandmarc commented on sdmx/tests/test_source.py
> +    assert len(source_ids) == 18
@khaeru I have just rebased the branch and adjusted the number of sources in test_source.py.

2020-12-13 10:36 UTC, khaeru approved these changes
@bertrandmarc thanks for rebasing. I went ahead and added the [requested](https://github.com/khaeru/sdmx/pull/32#pullrequestreview-545044071) line to whatsnew.rst.

The 'lint' check failure on your last commit was because there was only 1 blank line above/below the added class `TestNBB` in test_sources.py; PEP-8 requires 2 blank lines. Running [black](https://black.readthedocs.io/en/stable/) on code before submitting it will ensure this check passes.

Approved, and will merge once checks finish.

2020-12-13 10:37 UTC, merged

2020-12-14 08:40 UTC, khaeru commented
@bertrandmarc seems I was too hasty and merged this without checking myself that the test data query works. It doesn't:
https://github.com/khaeru/sdmx/runs/1548087118?check_suite_focus=true#step:8:857
```
E           ValueError: can't determine a SDMX reader for response content type 'text/html; charset=utf-8'

sdmx/api.py:457: ValueError
----------------------------- Captured stderr call -----------------------------
2020-12-14 05:18:43,482 sdmx.api - INFO: Requesting resource from https://stat.nbb.be/sdmx-json/data/REGPOP/POPULA.000.A?startTime=2013&endTime=2017
2020-12-14 05:18:43,482 sdmx.api - INFO: with headers {'User-Agent': 'python-requests/2.25.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}
------------------------------ Captured log call -------------------------------
INFO     sdmx.api:api.py:404 Requesting resource from https://stat.nbb.be/sdmx-json/data/REGPOP/POPULA.000.A?startTime=2013&endTime=2017
INFO     sdmx.api:api.py:405 with headers {'User-Agent': 'python-requests/2.25.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}
```

So indeed when I visit this URL I get an HTML error page: https://stat.nbb.be/sdmx-json/data/REGPOP/POPULA.000.A?startTime=2013&endTime=2017

Can you let me know:
- Did you run this test? Did it ever pass?
- If not, can you give a specific JSON URL for this service that is known to work?
- The link you added to the API documentation ([here](https://www.nbb.be/doc/dq/migratie_belgostat/en/nbb_stat-technical-manual.pdf)) doesn't contain any concrete description of the JSON service; it only has a broken link to the OECD's website. Is there another place you consulted for information on how to use this service?

2020-12-14 08:47 UTC, khaeru commented
The following appear to work:

- https://stat.nbb.be/sdmx-json/data/REGPOP/
- [https://stat.nbb.be/sdmx-json/data/REGPOP/POPULA..](https://stat.nbb.be/sdmx-json/data/REGPOP/POPULA..)
- [https://stat.nbb.be/sdmx-json/data/REGPOP/POPULA.000.](https://stat.nbb.be/sdmx-json/data/REGPOP/POPULA.000.)
- [https://stat.nbb.be/sdmx-json/data/REGPOP/POPULA.000+100.](https://stat.nbb.be/sdmx-json/data/REGPOP/POPULA.000+100.) etc.

It seems adding the "A" (for FREQ = Annual) at the end of the query is what triggers the error page, so I guess it is some flaw in the server?

2020-12-15 13:47 UTC, bertrandmarc commented
@khaeru Sorry I had not tested the test. I just took a working request and made narrower (to avoid downloading the full table). I thought Github test would show if there was an issue...

2020-12-15 23:17 UTC, khaeru commented
No problem! To be clear (I should probably write this somewhere more prominent), the tests of every single data source and endpoint are only run on a schedule once per day. This is because they are slow and somewhat ‘fragile’ (break unpredictably e.g. if the services are offline), so they would be (were once) very annoying to deal with when working on a PR.

However, this means we need to remember to run them manually when they are added to/modified. I also forgot to do this.

I'll make another PR to update with one of the URLs listed above. If the failing queries are a problem that is known at NBB or they plan a fix, we could also mention that in the docs.